### ISSUE TITLE
how to add example values to request body properties?

### ISSUE THREAD

**Issue by gusparr28** [fastify/fastify-swagger#696] opened 2022-11-29 17:23 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by gusparr28** [comment] 2022-11-29 18:03
> 

Yup, that's what I'm asking for. I tried that solution before opening the issue but didn't work for me. I have this body:

`  body: {
    type: 'object',
    required: ['username', 'password', 'trustId'],
    properties: {
      username: {
        description: 'Username for login',
        type: 'string',
      },
      password: {
        description: 'Password for login',
        type: 'string',
      },
      trustId: {
        description: 'Device trust id',
        type: 'string',
      },
    },
    examples: [
      {
        username: '123456785',
      },
      {
        password: 'Testtest1!',
      },
      {
        trustId: v4(),
      },
    ],
  }`

and I can't see the example values in my Swagger UI

**Comment by Eomm** [comment] 2022-11-29 18:08
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by Uzlopak** [comment] 2022-11-29 18:20
You should use example and not examples property. 
https://swagger.io/docs/specification/adding-examples/

**Comment by gusparr28** [comment] 2022-11-29 18:34
> You should use example and not examples property. https://swagger.io/docs/specification/adding-examples/

it looks like example property does not exist

Just tried these both and I got compiling error:

```
body: {
    type: 'object',
    required: ['username', 'password', 'trustId'],
    properties: {
      username: {
        description: 'Username for login',
        type: 'string',
      },
      password: {
        description: 'Password for login',
        type: 'string',
      },
      trustId: {
        description: 'Device trust id',
        type: 'string',
      },
    },
    example: {
      username: '123456785',
      password: 'Testtest1!',
      trustId: v4(),
    },
  }
```

```
  body: {
    type: 'object',
    required: ['username', 'password', 'trustId'],
    properties: {
      username: {
        description: 'Username for login',
        type: 'string',
      },
      password: {
        description: 'Password for login',
        type: 'string',
      },
      trustId: {
        description: 'Device trust id',
        type: 'string',
      },
    },
    example: [
      {
        username: '123456785',
      },
      {
        password: 'Testtest1!',
      },
      {
        trustId: v4(),
      },
    ],
  }
```

````
    err: {
      "type": "FastifyError",
      "message": "Failed building the validation schema for POST:, due to error strict mode: unknown keyword: \"example\"",      
      "stack":
          FastifyError: Failed building the validation schema for POST, due to error strict mode: unknown keyword: "example"    
      "name": "FastifyError",
      "code": "FST_ERR_SCH_VALIDATION_BUILD",
      "statusCode": 500
    }
```

**Comment by Uzlopak** [comment] 2022-11-29 18:44
You could also try to put the example into each property.

**Comment by gusparr28** [comment] 2022-11-29 19:04
> You could also try to put the example into each property.

it was my first try but didn't work, still got compiling error. In response body works like a charm, but in request body I don't find a way of how to add example values. Already thinking to change to static mode

**Comment by climba03003** [comment] 2022-11-30 06:27
Just curious, are you using `Swagger 2.0` or `OpenAPI 3.0`.
AFAIK, if you are using `Swagger 2.0`. There are [NO example](https://swagger.io/docs/specification/2-0/describing-parameters/) for body, only description.

I am closing this issue because I think it is a correct behavior.
If you are using `OpenAPI 3.0`, then please provide a minimal reproducible code that we can run directly.

**Closed by climba03003** 2022-11-30 06:27 UTC
